server:
  port: 8080
spring:
  data.mongodb:
   host: localhost
   port: 27017
   database: local
  jackson:
    default-property-inclusion: non_null
logging:
  level:
    org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping: TRACE